name: k6 Load Test

on:
  workflow_dispatch:  # manual trigger
  push:
    paths:
      - 'load-test-k6/**'

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        
      - name: Run load tests
        uses: grafana/run-k6-action@v1 
        with:
          path: load-tests-k6/tests/api_test.js
